"""events

Revision ID: 5ba8c7af7acc
Revises: e89fac9fa0b5
Create Date: 2019-07-23 15:29:37.920215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import adsputils

# revision identifiers, used by Alembic.
revision = '5ba8c7af7acc'
down_revision = 'e89fac9fa0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created', adsputils.UTCDateTime(timezone=True), nullable=True),
    sa.Column('updated', adsputils.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event', schema='public')
    # ### end Alembic commands ###
